### ISSUE TITLE
HA 2023.5  - AttributeError: 'ConfigEntries' object has no attribute 'async_setup_platforms'

### ISSUE THREAD

**Issue by h4fn3rb** [killer0071234/ha-hiq#47]
## Controller Model

Cybro2

## Describe the bug

After upgrading HA to 2023.5  integration failed to set up
## Debug log

```
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 387, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/hiq/__init__.py", line 28, in async_setup_entry
    hass.config_entries.async_setup_platforms(entry, PLATFORMS)
AttributeError: 'ConfigEntries' object has no attribute 'async_setup_platforms'

```
